### ISSUE TITLE
plugin not valid error

### ISSUE THREAD

**Issue by cailintrimble** [UCSCLibrary/NuxeoLink#14]
Plugin shows up on the admin page but with the an error message saying the plugin is not valid. See attached screen shot.
![screen shot 2015-12-09 at 9 07 36 am](https://cloud.githubusercontent.com/assets/16228010/11692448/5d05a37a-9e54-11e5-8ed7-401228a3c888.png)

**Comment by NedHenry** [comment]
Thanks for trying out the plugin. This error is often the result of a
misnamed plugin directory. The directory containing the plugin is sometimes
renamed automatically while downloading or unzipping. Make sure that the
plugin files get unzipped to a directory named simply NuxeoLink, and that
this is readable by the web server. Let us know if you continue to have
problems after trying this.
Best,
Ned
