### ISSUE TITLE
Can't select "UCLDC Schema" box after reinstalling plugin

### ISSUE THREAD

**Issue by ucmlibrary** [UCSCLibrary/NuxeoLink#8]
Hello,

I tried uninstalling the plugin to install a newer version. The uninstallation and consequent installation both appeared to be successful, but when I tried to enable the "UCLDC Schema" in the configuration screen, I got this error message: "Name: Name of element set must be unique."

**Comment by NedHenry** [comment]
I reproduced this errorin version 1.1.8 after attempting to upgrade from an older version. I then released a new version (1.1.9) which handles upgrades and re-installs more smoothly. I was able to do upgrade from an old version, and to uninstall and reinstall the plugin without seeing any errors. Please upgrade to the latest version if you are still seeing error messages, and contact me if this problem persists in any form. Many thanks for your feedback!
